### ISSUE TITLE
Commenting shortcut not working

### ISSUE THREAD

**Issue by emichael** [erggo/sublime-dafny#1]
Comment highlighting seems to work, but the comment line shortcut (`Ctrl+/` on Windows/Linux) is not working. I'd send you a pull request, but I have no idea what I'm doing with sublime syntax definitions.

**Comment by tvi** [comment]
Done  38719b9

**Comment by emichael** [comment]
Last commit was 3 years ago, and then you get to this in 2 hours. Nice.   :clap:

**Comment by tvi** [comment]
I was so happy that maybe somebody is using it that I fixed it. I agree that the package needs more love. I needs updating and restructuring, but I never found motivation to do it because I though that nobody is using it.

**Comment by emichael** [comment]
This package saved me from having to use vim for the first time in a long time. I wrote a quick and dirty Sublime build system to go with it, and now it's perfectly usable. So, thanks!!!

There are definitely some issues with the highlighting that could be cleaned up (string literals, for instance), but it's mostly readable.
